version: "3"
services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      .env
    networks:
      - project_network
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: . #local Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres_db
    env_file:
      .env
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  postgres:
